name: Python package

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11", "pypy3.10"]
        minizinc-version: ["2.8.7", "2.6.0"]

    env:
      MINIZINC_URL: https://github.com/MiniZinc/MiniZincIDE/releases/download/${{ matrix.minizinc-version }}/MiniZincIDE-${{ matrix.minizinc-version }}-x86_64.AppImage
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Add bin/ to PATH
        run: |
          mkdir -p ${{ github.workspace }}/bin
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
      - name: Install libfuse (AppImage dependency)
        run: |
          sudo apt-get update
          sudo apt-get install libfuse2 libegl1
      - name: Cache MiniZinc
        id: cache-minizinc
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/bin/minizinc
          key: ${{ env.MINIZINC_URL }}
      - name: Download MiniZinc
        if: steps.cache-minizinc.outputs.cache-hit != 'true'
        run: |
          sudo curl -o ${{ github.workspace }}/bin/minizinc -L $MINIZINC_URL
          sudo chmod +x ${{ github.workspace }}/bin/minizinc
          minizinc --version
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --dev
      - name: Run Pytest
        run: uv run pytest
      - name: Install numpy
        run: uv pip install numpy
      - name: Run Pytest with numpy
        run: uv run pytest

  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Install the project
        run: uv sync --dev
      - name: Check Ruff linter
        run: uv run ruff check
      - name: Check Ruff formatter
        run: uv run ruff format --check
      - name: Check MyPy type checker
        run: uv run mypy .

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Install the project
        run: uv sync --extra docs
      - name: Generate the documentation
        run: uv run sphinx-build -b html docs dist/docs
      - name: Check the documentation doesn't have broken links
        run: uv run sphinx-build -b linkcheck docs dist/docs
      - uses: actions/upload-artifact@v5
        with:
          name: documentation
          path: dist/docs/
